# Generated by Django 3.1.7 on 2021-03-22 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csvfile', models.FileField(blank=True, null=True, upload_to='csv_uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='MailSentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=200, null=True)),
                ('receiver', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SMTPEmailAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_username', models.CharField(blank=True, max_length=200, null=True)),
                ('smtp_password', models.CharField(blank=True, max_length=200, null=True)),
                ('smtp_host', models.CharField(blank=True, max_length=200, null=True)),
                ('smtp_port', models.CharField(blank=True, choices=[('587', '587'), ('25', '25'), ('465', '465'), ('2525', '2525')], default='587', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailSentCelery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('at_time', models.TimeField(auto_now=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.smtpemailaccount')),
            ],
        ),
    ]
