# Generated by Django 3.1.7 on 2021-03-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsentcelery',
            name='csv_name',
            field=models.CharField(default='hello', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailsentstatus',
            name='csv_name',
            field=models.CharField(default='hello', max_length=500),
            preserve_default=False,
        ),
    ]
