# Generated by Django 3.1.7 on 2021-04-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20210322_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsentstatus',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mailsentstatus',
            name='open_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
