# Generated by Django 3.1.4 on 2021-10-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_bde',
            field=models.BooleanField(default=False),
        ),
    ]
