# Generated by Django 3.1.4 on 2021-10-28 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20211027_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='salary',
        ),
    ]
