# Generated by Django 3.1.4 on 2021-10-06 10:34

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('birthday_date', models.DateField()),
                ('employee_name', models.CharField(max_length=500)),
                ('emp_image', models.ImageField(upload_to='upload/')),
                ('body', wagtail.core.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewjoineePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(max_length=500, verbose_name='Employee Name')),
                ('designation', models.CharField(max_length=255, verbose_name='Emploee Designation')),
                ('emp_image', models.ImageField(upload_to='upload/')),
                ('body', wagtail.core.fields.RichTextField()),
                ('joining_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsAddPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('emp_image', models.ImageField(upload_to='upload/')),
                ('body', wagtail.core.fields.RichTextField()),
                ('color', wagtail_color_panel.fields.ColorField(max_length=7)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='UpcomingHolidayPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=500)),
                ('emp_image', models.ImageField(upload_to='upload/')),
                ('body', wagtail.core.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
