# Generated by Django 3.1.4 on 2021-03-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignrecipient',
            name='link_clicked_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='opens_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
