# Generated by Django 3.1.4 on 2021-03-09 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20210309_1739'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampaignStatistic',
        ),
    ]
