# Generated by Django 3.1.4 on 2021-01-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_auto_20210106_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestedupdatefundraiser',
            name='beneficiaryAge',
        ),
        migrations.RemoveField(
            model_name='requestedupdatefundraiser',
            name='beneficiaryDocument',
        ),
        migrations.RemoveField(
            model_name='requestedupdatefundraiser',
            name='beneficiaryFullName',
        ),
        migrations.RemoveField(
            model_name='requestedupdatefundraiser',
            name='beneficiaryGender',
        ),
        migrations.RemoveField(
            model_name='requestedupdatefundraiser',
            name='beneficiaryPhoto',
        ),
        migrations.RemoveField(
            model_name='requestedupdatefundraiser',
            name='cause',
        ),
        migrations.RemoveField(
            model_name='requestedupdatefundraiser',
            name='cityOfResidence',
        ),
        migrations.RemoveField(
            model_name='requestedupdatefundraiser',
            name='goalAmount',
        ),
        migrations.RemoveField(
            model_name='requestedupdatefundraiser',
            name='isPrivate',
        ),
        migrations.RemoveField(
            model_name='requestedupdatefundraiser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='requestedupdatefundraiser',
            name='lastDateToFund',
        ),
        migrations.RemoveField(
            model_name='requestedupdatefundraiser',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='requestedupdatefundraiser',
            name='story',
        ),
        migrations.RemoveField(
            model_name='requestedupdatefundraiser',
            name='title',
        ),
        migrations.AddField(
            model_name='requestedupdatefundraiser',
            name='description',
            field=models.TextField(default='a', max_length=5000),
            preserve_default=False,
        ),
    ]
