# Generated by Django 3.1.4 on 2021-10-06 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(auto_now_add=True)),
                ('attendance_time', models.TimeField(auto_now=True)),
                ('attendance_status', models.CharField(choices=[('INTIME', 'In_Time'), ('OUTTIME', 'Out_Time')], max_length=15)),
                ('break_time', models.DurationField(default=datetime.time(0, 0))),
                ('working_time', models.DurationField(default=datetime.time(0, 0))),
            ],
        ),
    ]
