# Generated by Django 3.1.4 on 2021-01-06 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0003_auto_20210106_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='goalAmount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(200)]),
        ),
    ]
