# Generated by Django 3.1.4 on 2021-10-19 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Employee Name')),
            ],
        ),
        migrations.CreateModel(
            name='POCList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, unique=True, verbose_name='Project Name')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('client_name', models.CharField(max_length=255, verbose_name='Client Name')),
                ('project_description', models.TextField()),
                ('client_documentation', models.FileField(blank=True, null=True, upload_to='poc_client_documentation/')),
                ('company_documentation', models.FileField(blank=True, null=True, upload_to='poc_company_documentation/')),
                ('number_of_emp', models.PositiveIntegerField()),
                ('is_active', models.BooleanField()),
                ('assign', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('start_date', models.DateField()),
                ('dead_line', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('client_name', models.CharField(max_length=200)),
                ('company_document', models.FileField(blank=True, null=True, upload_to='company_document')),
                ('client_document', models.FileField(blank=True, null=True, upload_to='client_document')),
                ('status', models.CharField(choices=[('1', 'High'), ('2', 'Medium'), ('3', 'Low')], default=1, max_length=7)),
                ('number_of_emp', models.PositiveIntegerField()),
                ('is_active', models.BooleanField()),
                ('assign', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PocWorkEmployees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('emp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_tracking.poclist')),
            ],
        ),
        migrations.CreateModel(
            name='OccupiedEmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('emp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_tracking.project')),
            ],
        ),
    ]
