# Generated by Django 3.2.3 on 2021-10-21 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusinessShortCode', models.IntegerField(default=174379)),
                ('Password', models.CharField(max_length=255)),
                ('Timestamp', models.CharField(max_length=255)),
                ('TransactionType', models.CharField(default='CustomerPayBillOnline', max_length=255)),
                ('Amount', models.IntegerField(default=1)),
                ('PartyA', models.IntegerField()),
                ('PartyB', models.IntegerField(default=174379)),
                ('PhoneNumber', models.IntegerField()),
                ('CallBackURL', models.URLField(default='http://54.70.54.216:3000/callback/')),
                ('AccountReference', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'verbose_name': 'MPayment',
                'verbose_name_plural': 'MPayment',
                'db_table': 'MPayment',
            },
        ),
    ]
