# Generated by Django 3.1.1 on 2021-06-25 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=255)),
                ('other_p_type', models.CharField(blank=True, max_length=255, null=True, verbose_name=models.ManyToManyField(to='plants.PlantType'))),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('status', models.CharField(blank=True, choices=[('available', 'AVAILABLE'), ('taken', 'TAKEN'), ('not_available', 'NOT_AVAILABLE')], default='available', max_length=32, null=True)),
                ('datetime', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_type',
            field=models.ManyToManyField(to='plants.PlantType'),
        ),
    ]
