# Generated by Django 3.0.3 on 2021-01-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonorTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('contributeAnonimusly', models.BooleanField(default=False)),
                ('billingCity', models.CharField(max_length=1000)),
                ('country_code', models.CharField(max_length=1000)),
                ('country_name', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('postal', models.CharField(max_length=1000)),
                ('latitude', models.CharField(max_length=1000)),
                ('longitude', models.CharField(max_length=1000)),
                ('IPv4', models.CharField(max_length=1000)),
                ('state', models.CharField(max_length=1000)),
            ],
        ),
    ]
