# Generated by Django 3.1.4 on 2021-10-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=100)),
                ('file_type', models.CharField(blank=True, choices=[('policy', 'Policy'), ('form', 'Form')], max_length=6, null=True)),
                ('file', models.FileField(null=True, upload_to='file/')),
                ('date_time', models.DateTimeField(verbose_name='Date and Time')),
            ],
        ),
    ]
