# Generated by Django 3.2.3 on 2021-10-21 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brand',
                'db_table': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Cart',
                'db_table': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='icon/')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Colour',
                'verbose_name_plural': 'Colour',
                'db_table': 'Colour',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FeatureDeal', 'feature deal'), ('PopularDeal', 'popular deal'), ('DealOfTheMonth', 'Deal of the Month')], max_length=255, unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deal',
                'db_table': 'Deal',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0.0)),
                ('price_type', models.CharField(blank=True, max_length=150, null=True)),
                ('sale_price', models.FloatField(default=0.0)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('sku', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='Advertisement')),
                ('depot', models.IntegerField(default=0)),
                ('is_sale', models.BooleanField(default=True)),
                ('inventory', models.IntegerField(default=0)),
                ('discount_percent', models.FloatField(default=0.0)),
                ('product_option', models.CharField(choices=[('Booking', 'Booking'), ('Buy', 'Buy')], max_length=255)),
                ('visit_product', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'ProductCategory',
                'verbose_name_plural': 'ProductCategory',
                'db_table': 'ProductCategory',
            },
        ),
        migrations.CreateModel(
            name='ProductColour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'ProductColour',
                'verbose_name_plural': 'ProductColour',
                'db_table': 'ProductColour',
            },
        ),
        migrations.CreateModel(
            name='ProductDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ProductDeal',
                'verbose_name_plural': 'ProductDeal',
                'db_table': 'ProductDeal',
            },
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='description/')),
            ],
            options={
                'verbose_name': 'ProductDescription',
                'verbose_name_plural': 'ProductDescription',
                'db_table': 'ProductDescription',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image1', models.ImageField(upload_to='product/images')),
                ('product_image2', models.ImageField(blank=True, null=True, upload_to='product/images')),
                ('product_image3', models.ImageField(blank=True, null=True, upload_to='product/images')),
                ('product_image4', models.ImageField(blank=True, null=True, upload_to='product/images')),
            ],
            options={
                'verbose_name': 'ProductImage',
                'verbose_name_plural': 'ProductImage',
                'db_table': 'ProductImage',
            },
        ),
        migrations.CreateModel(
            name='ProductQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'ProductQuestion',
                'verbose_name_plural': 'ProductQuestion',
                'db_table': 'ProductQuestion',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('star_point', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'ProductReview',
                'verbose_name_plural': 'ProductReview',
                'db_table': 'ProductReview',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'ProductSize',
                'verbose_name_plural': 'ProductSize',
                'db_table': 'ProductSize',
            },
        ),
        migrations.CreateModel(
            name='ProductSubProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_or_weight', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Size',
                'db_table': 'Size',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sliders')),
                ('url', models.URLField(blank=True, default='https://www.dealzmoto.com/', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Slider',
                'db_table': 'Slider',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('bluetooth', models.BooleanField(default=False)),
                ('battery_life', models.CharField(max_length=100)),
                ('wireless', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('mobile_number', models.CharField(max_length=13)),
                ('website', models.URLField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='store')),
                ('describe', models.TextField()),
                ('store_portal_admin', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Store',
                'db_table': 'Store',
            },
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Category',
                'db_table': 'Sub Category',
            },
        ),
        migrations.CreateModel(
            name='SubProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subproduct_name', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('sale_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('discount_percent', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tag',
                'db_table': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'WishList',
                'verbose_name_plural': 'WishList',
                'db_table': 'WishList',
            },
        ),
    ]
