# Generated by Django 3.2.3 on 2021-10-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproduct',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='subproduct_name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
