# Generated by Django 3.2.3 on 2021-10-21 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211021_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductSubProduct',
        ),
    ]
